// Generated by LiveScript 1.2.0
var ConfigurationError, NotImplementedError, base, VALID_METHODS;
ConfigurationError = require('./exceptions').ConfigurationError;
NotImplementedError = require('./exceptions').NotImplementedError;
base = module.exports;
VALID_METHODS = ['get', 'post', 'put', 'patch', 'delete', 'head', 'copy', 'options'];
base.controller = {
  path: null,
  allowedMethods: VALID_METHODS,
  get: function(){
    throw new NotImplementedError('overload `get` in subclass');
  },
  post: function(){
    throw new NotImplementedError('overload `post` in subclass');
  },
  put: function(){
    throw new NotImplementedError('overload `put` in subclass');
  },
  patch: function(){
    throw new NotImplementedError('overload `patch` in subclass');
  },
  'delete': function(){
    throw new NotImplementedError('overload `delete` in subclass');
  },
  head: function(){
    throw new NotImplementedError('overload `head` in subclass');
  },
  copy: function(){
    throw new NotImplementedError('overload `copy` in subclass');
  },
  options: function(){
    var v;
    this.res.set({
      'Content-Length': '0',
      'Content-Type': 'text/plain',
      'Allow': (function(){
        var i$, ref$, len$, results$ = [];
        for (i$ = 0, len$ = (ref$ = this.allowedMethods).length; i$ < len$; ++i$) {
          v = ref$[i$];
          results$.push(v.toUpperCase());
        }
        return results$;
      }.call(this)).join(', ')
    });
    this.res.send(200);
  },
  notSupported: function(){
    this.res.send(405, 'Method not supported');
  },
  requestMethodName: function(){
    return this.req.route.method.toLowerCase();
  },
  dispatch: function(){
    var verb;
    verb = this.requestMethodName();
    if (!in$(verb, this.allowedMethods)) {
      this.notSupported();
      return;
    }
    if (this[verb] != null) {
      this[verb]();
    } else {
      throw new ConfigurationError("No handler method for " + verb);
    }
  },
  handle: function(req, res, next){
    var x$, o;
    x$ = o = clone$(this);
    x$.req = req;
    x$.res = res;
    x$.next = next;
    x$.dispatch();
    return x$;
  },
  route: function(app){
    var i$, ref$, len$, verb;
    if (this.allowedMethods.length === 0) {
      throw new ConfigurationError("No allowed methods specified");
    }
    for (i$ = 0, len$ = (ref$ = this.allowedMethods).length; i$ < len$; ++i$) {
      verb = ref$[i$];
      if (!in$(verb, VALID_METHODS)) {
        throw new ConfigurationError(verb + " is not a valid HTTP verb");
      }
    }
    if (this.path == null) {
      throw new ConfigurationError("No path defined for this controller");
    }
    app.all(this.path, this.handle);
  }
};
function in$(x, xs){
  var i = -1, l = xs.length >>> 0;
  while (++i < l) if (x === xs[i]) return true;
  return false;
}
function clone$(it){
  function fun(){} fun.prototype = it;
  return new fun;
}