// Generated by LiveScript 1.2.0
var base, template, index;
base = require('./base');
template = require('./template');
index = module.exports;
index.controller = base.controller;
index.templateController = template.templateController;